### PR TITLE
Update dbFuncs.go

### PR DESCRIPTION
**Pull request by pieromqwerty**
Modified the file naming system to 1 in 100 chance of adding `niceturtlclone` to the beginning of the file name.

### CODE REVIEW

**Comment by Polairr** [comment]
For one, `rand.Intn()` will return the same thing every time, since you didn't set the seed. Secondly, `niceturtlclone` isn't defined.

**Comment by Polairr** [comment]
Also, `math/rand` wasn't imported

**Comment by Polairr** [comment]
no

**Comment by pieromqwerty** [comment]
you fuckwad it was imported

**Comment by Polairr** [comment]
Still, no.

**Pull request closed without merging**
